### ISSUE TITLE
[BUG] - Enter a descriptive title

### ISSUE THREAD

**Issue by tzarger** [vultr/cert-manager-webhook-vultr#52]
**Describe the bug**
I followed the Readme as close as possible and trying to get a wildcard cert from LetsEncrypt Staging. It seems that that might be some permission issue and feel I missed something. I installed it via: https://artifacthub.io/packages/helm/vultr/cert-manager-webhook-vultr. I get a PresentError due to Forbidden error.

**To Reproduce**
1. Installed cert-manager

2. Applied "vultr-credentials" via command line with a Base64 Encoded version of my API Key - I even tried to allow all IPV4 Addresses on this API Key as I am not sure what subnet or IP address to limit for this.

3. helm install cert-manager-webhook-vultr vultr/cert-manager-webhook-vultr --version 1.0.0

4. Applied all the examples as one file, including: ClusterIssuer, Role, RoleBinding and Certificate
5.  `kubectl get certificate`
```
NAME                                     READY   SECRET                                   AGE
cert-manager-webhook-vultr-ca            True    cert-manager-webhook-vultr-ca            79m
cert-manager-webhook-vultr-webhook-tls   True    cert-manager-webhook-vultr-webhook-tls   79m
staging-mmgm-com                         False   staging-mmgm-tls                         76m
```
6. `kubectl describe challenges`
```
Status:
  Presented:   false
  Processing:  true
  Reason:      vultr.acme.mmgm.com is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "vultr" in API group "acme.mmgm.com" at the cluster scope
  State:       pending
Events:
  Type     Reason        Age              From          Message
  ----     ------        ----             ----          -------
  Normal   Started       9s               cert-manager  Challenge scheduled for processing
  Warning  PresentError  4s (x3 over 9s)  cert-manager  Error presenting challenge: vultr.acme.mmgm.com is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "vultr" in API group "acme.mmgm.com" at the cluster scope
  ```

**Expected behavior**
Certificate to be issued.

**Additional context**
I have not applied my ingress yaml yet as I we hoping to see the Certificate to be issued. Anything you can point me to as to what I am missing, would be greatly appreciated.

**Comment by ddymko** [comment]
@tzarger 

Hey there, I would recommend install by following the readme https://github.com/vultr/cert-manager-webhook-vultr#installation


I believe we may need to update artifacthub.


Also, you are correct that appears to have invalid RBAC definitions set

**Comment by tzarger** [comment]
Hello @ddymko I am pretty sure some progress, but not entirely sure everything is working.

1. Should there be any DNS entries added to prove DNS Ownership?
2. I have not received any emails at the email I added in the ClusterIssuer
3. It appears the OrderCreated was the last status and not sure how long that should take.

`kubectl get secrets -n cert-manager`
```
NAME                                               TYPE                                  DATA   AGE
cert-manager-cainjector-token-vrjt7                kubernetes.io/service-account-token   3      61m
cert-manager-token-5t4rw                           kubernetes.io/service-account-token   3      61m
cert-manager-webhook-ca                            Opaque                                3      61m
cert-manager-webhook-token-zdvtz                   kubernetes.io/service-account-token   3      61m
cert-manager-webhook-vultr-ca                      kubernetes.io/tls                     3      51m
cert-manager-webhook-vultr-token-rmc4v             kubernetes.io/service-account-token   3      27m
cert-manager-webhook-vultr-webhook-tls             kubernetes.io/tls                     3      51m
default-token-628tw                                kubernetes.io/service-account-token   3      61m
letsencrypt-staging                                Opaque                                1      35m
sh.helm.release.v1.cert-manager-webhook-vultr.v1   helm.sh/release.v1                    1      27m
vultr-credentials                                  Opaque                                1      59m
```

`kubectl get certificate`
```            
NAME               READY   SECRET             AGE
staging-mmgm-com   False   staging-mmgm-tls   32m
```

`kubectl describe certificaterequest`
```
Status:
  Conditions:
    Last Transition Time:  2022-06-03T02:26:42Z
    Message:               Certificate request has been approved by cert-manager.io
    Reason:                cert-manager.io
    Status:                True
    Type:                  Approved
    Last Transition Time:  2022-06-03T02:26:42Z
    Message:               Waiting on certificate issuance from order default/staging-mmgm-com-l4gvt-3136983109: "pending"
    Reason:                Pending
    Status:                False
    Type:                  Ready
Events:
  Type    Reason           Age   From          Message
  ----    ------           ----  ----          -------
  Normal  cert-manager.io  32m   cert-manager  Certificate request has been approved by cert-manager.io
  Normal  OrderCreated     32m   cert-manager  Created Order resource default/staging-mmgm-com-l4gvt-3136983109
```

As you can see, 32 minutes and waiting. So I am wonder if there is something missing. Maybe the API Token is not working from the `vultr-credentials` secret?

By the way, I also had a friend send me an email to confirm the email was working.

If you need to see the ClusterIssue, Role, RoleBinding or Certificate, let me know how to send privately, I do not want me email and domain info posted here in public.

Thank you.

**Comment by tzarger** [comment]
@ddymko So it seems that main issue may be the fact that the DNS entries in domain is never updated with `_acme-challenge` and when running the test I receive this error:

```
bash scripts/fetch-test-binaries.sh
TEST_ASSET_ETCD="/Users/troy/.kube/cert-manager-webhook-vultr-master/_out/kubebuilder/bin/etcd" TEST_ASSET_KUBE_APISERVER="/Users/troy/.kube/cert-manager-webhook-vultr-master/_out/kubebuilder/bin/kube-apiserver" TEST_ASSET_KUBECTL="/Users/troy/.kube/cert-manager-webhook-vultr-master/_out/kubebuilder/bin/kubectl" \
	go test -v .
=== RUN   TestRunsSuite
=== RUN   TestRunsSuite/Conformance
=== RUN   TestRunsSuite/Conformance/Basic
=== RUN   TestRunsSuite/Conformance/Basic/PresentRecord
    util.go:71: error creating test fixtures: exit status 1
=== RUN   TestRunsSuite/Conformance/Extended
=== RUN   TestRunsSuite/Conformance/Extended/DeletingOneRecordRetainsOthers
    suite.go:73: skipping test as strict mode is disabled, see: https://github.com/jetstack/cert-manager/pull/1354
--- FAIL: TestRunsSuite (25.27s)
    --- FAIL: TestRunsSuite/Conformance (14.27s)
        --- FAIL: TestRunsSuite/Conformance/Basic (3.36s)
            --- FAIL: TestRunsSuite/Conformance/Basic/PresentRecord (3.36s)
        --- PASS: TestRunsSuite/Conformance/Extended (0.00s)
            --- SKIP: TestRunsSuite/Conformance/Extended/DeletingOneRecordRetainsOthers (0.00s)
FAIL
FAIL	github.com/vultr/cert-manager-webhook-vultr	25.640s
FAIL
make: *** [test] Error 1
```

**Comment by ddymko** [comment]
@tzarger 

I will have to go through this because I know this plugin works as I have used it in the past and written a post about it

https://www.dymko.me/posts/automatic-dns-tls-on-kubernetes/

We'll look through it

**Comment by ddymko** [comment]
Taking a quick look it looks like your RBAC definitions are causing the problems

```
vultr.mmgm.com is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "vultr" in API group "mmgm.com" at the cluster scope
```

**Comment by tzarger** [comment]
@ddymko I have copied the RBAC definitions multiple times from the GitHub Repo and now from your article above.

If I don't change the groupName in the cluster issuer, I get this (DNS updated as well)
```Status:
  Presented:   true
  Processing:  true
  Reason:      Waiting for DNS-01 challenge propagation: DNS record for "mmgm.com" not yet propagated
  State:       pending
Events:
  Type     Reason        Age                From          Message
  ----     ------        ----               ----          -------
  Normal   Started       58s                cert-manager  Challenge scheduled for processing
  Warning  PresentError  58s (x2 over 58s)  cert-manager  Error presenting challenge: the server is currently unable to handle the request (post vultr.acme.vultr.com)
  Normal   Presented     52s                cert-manager  Presented challenge using DNS-01 challenge mechanism
```

if I change the group name to something like: `groupName: acme.mmgm.com` I get this (and no DNS update)

```
Status:
  Presented:   false
  Processing:  true
  Reason:      vultr.acme.makemoneygrowmoney.com is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "vultr" in API group "acme.makemoneygrowmoney.com" at the cluster scope
  State:       pending
Events:
  Type     Reason        Age                From          Message
  ----     ------        ----               ----          -------
  Normal   Started       17s                cert-manager  Challenge scheduled for processing
  Warning  PresentError  12s (x3 over 17s)  cert-manager  Error presenting challenge: vultr.acme.mmgm.com is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "vultr" in API group "acme.mmgm.com" at the cluster scope

```

This is my RBAC in either case:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-vultr:secret-reader
  namespace: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["vultr-credentials"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-vultr:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-vultr:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-vultr
```

I noticed in the Role the apiGroup is an array of 1 empty string:
```rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["vultr-credentials"]
  verbs: ["get", "watch"]
  ```
  
  In the RoleBinding, roleRef has an apiGroup:
  ```
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: cert-manager-webhook-vultr:secret-reader
  ```
  
  In the RoleBinding the subjects again has no apiGroup:
  ```
  subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-vultr
    ```
    
    Since the permission is in the apiGroup:
    `  Warning  PresentError  12s (x3 over 17s)  cert-manager  Error presenting challenge: vultr.acme.mmgm.com is forbidden: User "system:serviceaccount:cert-manager:cert-manager" cannot create resource "vultr" in API group "acme.mmgm.com" at the cluster scope`
    
    Could this be the issue?

**Comment by tzarger** [comment]
@ddymko Started with a new cluster and saw this messsage:

`  Warning  PresentError  79s (x5 over 2m24s)  cert-manager  Error presenting challenge: {"error":"Unable to add record: New records TTL (60) must match the TTL of existing records (120)","status":400}`

It appears that the lowest TTL is 120 ... Is this something that should be adjusted? Or will this be an issue in the future when renewing the certificate?

Beyond that, I deleted my cluster, deleted the `_acme-challenge` DNS entry did the steps and everything worked this time.

It seems `groupName: acme.vultr.com` does work... in your repo, it says it should be my domain... but that seems to have the User permission issue.

Here is my latest ClusterIssuer and RBAC:

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: email@mmgm.com
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            groupName: acme.vultr.com
            solverName: vultr
            config:
              apiKeySecretRef:
                key: apiKey
                name: vultr-credentials
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: email@mmgm.com
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: acme.vultr.com
            solverName: vultr
            config:
              apiKeySecretRef:
                key: apiKey
                name: vultr-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-vultr:secret-reader
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vultr-credentials"]
    verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-vultr:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-vultr:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-vultr

```

**Comment by ddymko** [comment]
@tzarger 

@ErwinsExpertise can you look into this issue and see if you can find what the problem might be

**Comment by ErwinsExpertise** [comment]
@tzarger 

It's good to hear that it is working for you now. Can you share where you see the groupname should be your domain so we can clarify that? 

I went ahead and tested myself and was able to create a wildcard cert without any issues using the following manifests:

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: admin@lifeoferwin.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging
    solvers:
    - dns01:
        webhook:
          groupName: acme.vultr.com
          solverName: vultr
          config:
            apiKeySecretRef:
              key: apiKey
              name: vultr-credentials
---


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-vultr:secret-reader
  namespace: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["vultr-credentials"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-vultr:secret-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-vultr:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-vultr
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-cert-example-com
spec:
  commonName: "*.domain.com"
  dnsNames:
  - "*.domain.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: example-com-tls
```

As far as the TTL message is concerned we can look into adjusting this value to 120. A value of 60 seems to work without issue for me, however, we can look into that more.

The value is set in the code here:
https://github.com/vultr/cert-manager-webhook-vultr/blob/260d09a930f2d58558c11081ba4540925b6530fa/main.go#L93
